"""added reflection id

Revision ID: 15a5b0345a9b
Revises: c8488f7a5441
Create Date: 2026-08-01 19:28:38.636387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a5b0345a9b'
down_revision: Union[str, Sequence[str], None] = 'c8488f7a5441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_activities', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_family_activities_request_id'), 'family_activities', ['request_id'], unique=False)
    op.create_unique_constraint('uq_family_activity_request_id', 'family_activities', ['request_id'])
    op.add_column('journey_reflections', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_journey_reflections_request_id'), 'journey_reflections', ['request_id'], unique=False)
    op.create_unique_constraint('uq_journey_reflection_request', 'journey_reflections', ['user_id', 'request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_journey_reflection_request', 'journey_reflections', type_='unique')
    op.drop_index(op.f('ix_journey_reflections_request_id'), table_name='journey_reflections')
    op.drop_column('journey_reflections', 'request_id')
    op.drop_constraint('uq_family_activity_request_id', 'family_activities', type_='unique')
    op.drop_index(op.f('ix_family_activities_request_id'), table_name='family_activities')
    op.drop_column('family_activities', 'request_id')
    # ### end Alembic commands ###
