"""pending_email_cheanges

Revision ID: 29cec215c274
Revises: ef8974187265
Create Date: 2026-08-07 11:38:26.665953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29cec215c274"
down_revision: Union[str, Sequence[str], None] = "ef8974187265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_email_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("new_email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pending_email_changes_cancelled_at"),
        "pending_email_changes",
        ["cancelled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_email_changes_expires_at"),
        "pending_email_changes",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_email_changes_new_email"),
        "pending_email_changes",
        ["new_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_email_changes_token_hash"),
        "pending_email_changes",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_pending_email_changes_user_id"),
        "pending_email_changes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pending_email_changes_user_id"), table_name="pending_email_changes"
    )
    op.drop_index(
        op.f("ix_pending_email_changes_token_hash"), table_name="pending_email_changes"
    )
    op.drop_index(
        op.f("ix_pending_email_changes_new_email"), table_name="pending_email_changes"
    )
    op.drop_index(
        op.f("ix_pending_email_changes_expires_at"), table_name="pending_email_changes"
    )
    op.drop_index(
        op.f("ix_pending_email_changes_cancelled_at"),
        table_name="pending_email_changes",
    )
    op.drop_table("pending_email_changes")
    # ### end Alembic commands ###
