"""add_update_journey_reflection_endpoint

Revision ID: 69286f7ad8b8
Revises: b9f1d0e7a602
Create Date: 2026-08-08 10:05:34.118578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69286f7ad8b8'
down_revision: Union[str, Sequence[str], None] = 'b9f1d0e7a602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_bookmarks_book_id'), table_name='book_bookmarks')
    op.drop_index(op.f('ix_book_bookmarks_created_at'), table_name='book_bookmarks')
    op.drop_index(op.f('ix_book_bookmarks_id'), table_name='book_bookmarks')
    op.drop_index(op.f('ix_book_bookmarks_user_id'), table_name='book_bookmarks')
    op.drop_table('book_bookmarks')
    op.create_index(op.f('ix_journey_quran_progress_created_at'), 'journey_quran_progress', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_quran_progress_created_at'), table_name='journey_quran_progress')
    op.create_table('book_bookmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('book_bookmarks_book_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('book_bookmarks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('book_bookmarks_pkey')),
    sa.UniqueConstraint('user_id', 'book_id', name=op.f('uq_book_bookmark_user_book'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_book_bookmarks_user_id'), 'book_bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_book_bookmarks_id'), 'book_bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_book_bookmarks_created_at'), 'book_bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_bookmarks_book_id'), 'book_bookmarks', ['book_id'], unique=False)
    # ### end Alembic commands ###
