"""initial schema

Revision ID: 91740e749e36
Revises: 
Create Date: 2026-03-08 09:32:51.663192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91740e749e36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charities_id'), 'charities', ['id'], unique=False)
    op.create_table('sadaqah_acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('general', 'dhikr', 'community', 'donation', name='sadaqahcategory', native_enum=False), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_ramadan_only', sa.Boolean(), nullable=False),
    sa.Column('ramadan_multiplier', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('reward_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sadaqah_acts_id'), 'sadaqah_acts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('friday_reminder', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('evidence_mode', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('donation_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=True),
    sa.Column('english_text', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['sadaqah_acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_id'), 'evidences', ['id'], unique=False)
    op.create_table('family_jars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_stars', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_current_streak', sa.Integer(), nullable=True),
    sa.Column('group_longest_streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_jars_id'), 'family_jars', ['id'], unique=False)
    op.create_index(op.f('ix_family_jars_invite_code'), 'family_jars', ['invite_code'], unique=True)
    op.create_table('jars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_stars', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jars_id'), 'jars', ['id'], unique=False)
    op.create_index(op.f('ix_jars_user_id'), 'jars', ['user_id'], unique=False)
    op.create_table('sadaqah_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stars_earned', sa.Integer(), nullable=False),
    sa.Column('friday_boost', sa.Boolean(), nullable=False),
    sa.Column('ramadan_bonus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['sadaqah_acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'act_id', 'date', name='unique_daily_log')
    )
    op.create_index('idx_date', 'sadaqah_logs', ['date'], unique=False)
    op.create_index('idx_user_date', 'sadaqah_logs', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_act_id'), 'sadaqah_logs', ['act_id'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_id'), 'sadaqah_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_user_id'), 'sadaqah_logs', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    op.create_table('family_jar_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_jar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('stars_added', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['sadaqah_acts.id'], ),
    sa.ForeignKeyConstraint(['family_jar_id'], ['family_jars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_jar_logs_id'), 'family_jar_logs', ['id'], unique=False)
    op.create_table('family_jar_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_jar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_jar_id'], ['family_jars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_jar_members_id'), 'family_jar_members', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_family_jar_members_id'), table_name='family_jar_members')
    op.drop_table('family_jar_members')
    op.drop_index(op.f('ix_family_jar_logs_id'), table_name='family_jar_logs')
    op.drop_table('family_jar_logs')
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_sadaqah_logs_user_id'), table_name='sadaqah_logs')
    op.drop_index(op.f('ix_sadaqah_logs_id'), table_name='sadaqah_logs')
    op.drop_index(op.f('ix_sadaqah_logs_act_id'), table_name='sadaqah_logs')
    op.drop_index('idx_user_date', table_name='sadaqah_logs')
    op.drop_index('idx_date', table_name='sadaqah_logs')
    op.drop_table('sadaqah_logs')
    op.drop_index(op.f('ix_jars_user_id'), table_name='jars')
    op.drop_index(op.f('ix_jars_id'), table_name='jars')
    op.drop_table('jars')
    op.drop_index(op.f('ix_family_jars_invite_code'), table_name='family_jars')
    op.drop_index(op.f('ix_family_jars_id'), table_name='family_jars')
    op.drop_table('family_jars')
    op.drop_index(op.f('ix_evidences_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_table('donation_intents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sadaqah_acts_id'), table_name='sadaqah_acts')
    op.drop_table('sadaqah_acts')
    op.drop_index(op.f('ix_charities_id'), table_name='charities')
    op.drop_table('charities')
    op.drop_table('badges')
    # ### end Alembic commands ###
