"""initial schema

Revision ID: c8488f7a5441
Revises: 
Create Date: 2026-08-01 16:38:45.633055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8488f7a5441'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adhkar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_arabic', sa.Text(), nullable=False),
    sa.Column('text_translation', sa.Text(), nullable=False),
    sa.Column('time_of_day', sa.Enum('morning', 'evening', name='timeofday', native_enum=False), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adhkar_time_of_day'), 'adhkar', ['time_of_day'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_category'), 'books', ['category'], unique=False)
    op.create_index(op.f('ix_books_deleted_at'), 'books', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_published'), 'books', ['published'], unique=False)
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charities_id'), 'charities', ['id'], unique=False)
    op.create_index('ix_charities_verified_active_category', 'charities', ['is_verified', 'is_active', 'category'], unique=False)
    op.create_index('ix_charities_verified_active_featured', 'charities', ['is_verified', 'is_active', 'is_featured'], unique=False)
    op.create_table('leaderboard_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_seasons_id'), 'leaderboard_seasons', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboard_seasons_season_name'), 'leaderboard_seasons', ['season_name'], unique=True)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('strategy_config', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_category'), 'notification_templates', ['category'], unique=False)
    op.create_index(op.f('ix_notification_templates_enabled'), 'notification_templates', ['enabled'], unique=False)
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_key'), 'notification_templates', ['key'], unique=True)
    op.create_index(op.f('ix_notification_templates_strategy'), 'notification_templates', ['strategy'], unique=False)
    op.create_table('sadaqah_acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('general', 'dhikr', 'community', 'donation', 'kindness', 'prayer', 'family', 'knowledge', 'environment', 'character', name='sadaqahcategory', native_enum=False), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_ramadan_only', sa.Boolean(), nullable=False),
    sa.Column('ramadan_multiplier', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('reward_weight', sa.Integer(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sadaqah_acts_id'), 'sadaqah_acts', ['id'], unique=False)
    op.create_index('ix_sadaqah_acts_verified_ramadan', 'sadaqah_acts', ['verified', 'is_ramadan_only'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role', native_enum=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_data', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('MONEY', 'FOOD', 'KINDNESS', 'DHIKR', 'PRAYER', 'REMOVE_HARM', 'SMILE', 'TIME', name='activitytype', native_enum=False), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_type', name='uq_activity_streak')
    )
    op.create_index(op.f('ix_activity_streaks_activity_type'), 'activity_streaks', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_streaks_created_at'), 'activity_streaks', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_streaks_id'), 'activity_streaks', ['id'], unique=False)
    op.create_index(op.f('ix_activity_streaks_last_completed_at'), 'activity_streaks', ['last_completed_at'], unique=False)
    op.create_index(op.f('ix_activity_streaks_user_id'), 'activity_streaks', ['user_id'], unique=False)
    op.create_table('book_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_book_bookmark_user_book')
    )
    op.create_index(op.f('ix_book_bookmarks_book_id'), 'book_bookmarks', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_bookmarks_created_at'), 'book_bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_bookmarks_id'), 'book_bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_book_bookmarks_user_id'), 'book_bookmarks', ['user_id'], unique=False)
    op.create_table('book_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'chapter_number', name='uq_book_chapter_number')
    )
    op.create_index(op.f('ix_book_chapters_book_id'), 'book_chapters', ['book_id'], unique=False)
    op.create_index('ix_book_chapters_book_order', 'book_chapters', ['book_id', 'chapter_number'], unique=False)
    op.create_index(op.f('ix_book_chapters_id'), 'book_chapters', ['id'], unique=False)
    op.create_table('donation_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_intents_charity_id'), 'donation_intents', ['charity_id'], unique=False)
    op.create_index(op.f('ix_donation_intents_user_id'), 'donation_intents', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=True),
    sa.Column('english_text', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['sadaqah_acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_id'), 'evidences', ['id'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cover_icon', sa.String(length=64), nullable=True),
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_created_by'), 'families', ['created_by'], unique=False)
    op.create_index(op.f('ix_families_deleted_at'), 'families', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.create_table('jars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_stars', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jars_id'), 'jars', ['id'], unique=False)
    op.create_index(op.f('ix_jars_user_id'), 'jars', ['user_id'], unique=False)
    op.create_table('journey_adhkar_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adhkar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'adhkar_id', name='uq_journey_adhkar_favorite')
    )
    op.create_index(op.f('ix_journey_adhkar_favorites_adhkar_id'), 'journey_adhkar_favorites', ['adhkar_id'], unique=False)
    op.create_index(op.f('ix_journey_adhkar_favorites_created_at'), 'journey_adhkar_favorites', ['created_at'], unique=False)
    op.create_index(op.f('ix_journey_adhkar_favorites_id'), 'journey_adhkar_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_journey_adhkar_favorites_user_id'), 'journey_adhkar_favorites', ['user_id'], unique=False)
    op.create_table('journey_adhkar_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adhkar_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'adhkar_id', name='uq_journey_adhkar_progress')
    )
    op.create_index(op.f('ix_journey_adhkar_progress_adhkar_id'), 'journey_adhkar_progress', ['adhkar_id'], unique=False)
    op.create_index(op.f('ix_journey_adhkar_progress_created_at'), 'journey_adhkar_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_journey_adhkar_progress_id'), 'journey_adhkar_progress', ['id'], unique=False)
    op.create_index(op.f('ix_journey_adhkar_progress_user_id'), 'journey_adhkar_progress', ['user_id'], unique=False)
    op.create_table('journey_reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_journey_reading_progress')
    )
    op.create_index(op.f('ix_journey_reading_progress_book_id'), 'journey_reading_progress', ['book_id'], unique=False)
    op.create_index(op.f('ix_journey_reading_progress_chapter_number'), 'journey_reading_progress', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_journey_reading_progress_created_at'), 'journey_reading_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_journey_reading_progress_id'), 'journey_reading_progress', ['id'], unique=False)
    op.create_index(op.f('ix_journey_reading_progress_last_read_at'), 'journey_reading_progress', ['last_read_at'], unique=False)
    op.create_index(op.f('ix_journey_reading_progress_user_id'), 'journey_reading_progress', ['user_id'], unique=False)
    op.create_table('journey_reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=64), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_reflections_created_at'), 'journey_reflections', ['created_at'], unique=False)
    op.create_index(op.f('ix_journey_reflections_date'), 'journey_reflections', ['date'], unique=False)
    op.create_index(op.f('ix_journey_reflections_deleted_at'), 'journey_reflections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_journey_reflections_id'), 'journey_reflections', ['id'], unique=False)
    op.create_index('ix_journey_reflections_user_date', 'journey_reflections', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_journey_reflections_user_id'), 'journey_reflections', ['user_id'], unique=False)
    op.create_table('monthly_goal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('goals_completed', sa.Integer(), nullable=False),
    sa.Column('goals_active', sa.Integer(), nullable=False),
    sa.Column('total_acts_done', sa.Integer(), nullable=False),
    sa.Column('streak_at_review', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year_month', name='uq_user_monthly_review')
    )
    op.create_index(op.f('ix_monthly_goal_reviews_id'), 'monthly_goal_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_goal_reviews_user_id'), 'monthly_goal_reviews', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_idempotency_key'), 'notifications', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_used_at'), 'password_reset_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('sadaqah_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('response_current_stars', sa.Integer(), nullable=True),
    sa.Column('response_capacity', sa.Integer(), nullable=True),
    sa.Column('response_completed_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stars_earned', sa.Integer(), nullable=False),
    sa.Column('friday_boost', sa.Boolean(), nullable=False),
    sa.Column('ramadan_bonus', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['sadaqah_acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'act_id', 'date', name='unique_daily_log'),
    sa.UniqueConstraint('user_id', 'request_id', name='unique_sadaqah_log_request')
    )
    op.create_index('idx_date', 'sadaqah_logs', ['date'], unique=False)
    op.create_index('idx_user_date', 'sadaqah_logs', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_act_id'), 'sadaqah_logs', ['act_id'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_created_at'), 'sadaqah_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_id'), 'sadaqah_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_request_id'), 'sadaqah_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_sadaqah_logs_user_id'), 'sadaqah_logs', ['user_id'], unique=False)
    op.create_table('scheduled_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', 'local_date', name='uq_scheduled_notification_daily')
    )
    op.create_index('ix_scheduled_notifications_due', 'scheduled_notifications', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_notifications_scheduled_for'), 'scheduled_notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_notifications_user_id'), 'scheduled_notifications', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('push_token', sa.String(length=512), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('acts_target', sa.Integer(), nullable=False),
    sa.Column('acts_done', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', 'REPLACED', name='goalstatus', native_enum=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_goals_active', 'user_goals', ['user_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_user_goals_deleted_at'), 'user_goals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_index('ix_user_goals_month', 'user_goals', ['user_id', 'month', 'status'], unique=False)
    op.create_index(op.f('ix_user_goals_status'), 'user_goals', ['status'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('selected_mode', sa.Enum('PERSONAL', 'FAMILY', 'BOTH', name='usermode', native_enum=False), nullable=False),
    sa.Column('notification_preferences', sa.Text(), nullable=False),
    sa.Column('reminder_preferences', sa.Text(), nullable=False),
    sa.Column('accessibility_preferences', sa.Text(), nullable=False),
    sa.Column('privacy_preferences', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_revoked_at'), 'user_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    op.create_table('activity_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('MONEY', 'FOOD', 'KINDNESS', 'DHIKR', 'PRAYER', 'REMOVE_HARM', 'SMILE', 'TIME', name='activitytype', native_enum=False), nullable=False),
    sa.Column('context', sa.Enum('PERSONAL', 'FAMILY', 'BOTH', name='activitycontext', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('stars_earned', sa.Integer(), nullable=False),
    sa.Column('friday_boost', sa.Boolean(), nullable=False),
    sa.Column('ramadan_bonus', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_completions_activity_type'), 'activity_completions', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_completions_completed_at'), 'activity_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_activity_completions_context'), 'activity_completions', ['context'], unique=False)
    op.create_index(op.f('ix_activity_completions_created_at'), 'activity_completions', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_completions_deleted_at'), 'activity_completions', ['deleted_at'], unique=False)
    op.create_index('ix_activity_completions_family', 'activity_completions', ['family_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_activity_completions_family_id'), 'activity_completions', ['family_id'], unique=False)
    op.create_index(op.f('ix_activity_completions_id'), 'activity_completions', ['id'], unique=False)
    op.create_index('ix_activity_completions_user_date', 'activity_completions', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_activity_completions_user_id'), 'activity_completions', ['user_id'], unique=False)
    op.create_index('ix_activity_completions_user_type', 'activity_completions', ['user_id', 'activity_type'], unique=False)
    op.create_table('activity_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('MONEY', 'FOOD', 'KINDNESS', 'DHIKR', 'PRAYER', 'REMOVE_HARM', 'SMILE', 'TIME', name='activitytype', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('context', sa.Enum('PERSONAL', 'FAMILY', 'BOTH', name='activitycontext', native_enum=False), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_sessions_activity_type'), 'activity_sessions', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_sessions_context'), 'activity_sessions', ['context'], unique=False)
    op.create_index(op.f('ix_activity_sessions_created_at'), 'activity_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_sessions_deleted_at'), 'activity_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_sessions_family_id'), 'activity_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_id'), 'activity_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_started_at'), 'activity_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_activity_sessions_user_id'), 'activity_sessions', ['user_id'], unique=False)
    op.create_index('ix_activity_sessions_user_started', 'activity_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('family_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('FAMILY_CREATED', 'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_ROLE_CHANGED', 'GOAL_CREATED', 'GOAL_COMPLETED', 'PRAYER_REQUEST_CREATED', 'PRAYER_REQUEST_ANSWERED', 'REFLECTION_SHARED', 'INVITATION_ACCEPTED', 'INVITATION_DECLINED', 'ACT_ADDED', name='eventtype', native_enum=False), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_activities_actor_id'), 'family_activities', ['actor_id'], unique=False)
    op.create_index(op.f('ix_family_activities_event_type'), 'family_activities', ['event_type'], unique=False)
    op.create_index(op.f('ix_family_activities_family_id'), 'family_activities', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_activities_id'), 'family_activities', ['id'], unique=False)
    op.create_index('ix_family_activities_timeline', 'family_activities', ['family_id', 'created_at', 'id'], unique=False)
    op.create_table('family_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('acts_target', sa.Integer(), nullable=False),
    sa.Column('acts_done', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_goals_active', 'family_goals', ['family_id', 'is_archived', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_family_goals_created_by'), 'family_goals', ['created_by'], unique=False)
    op.create_index(op.f('ix_family_goals_deleted_at'), 'family_goals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_family_goals_family_id'), 'family_goals', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_goals_id'), 'family_goals', ['id'], unique=False)
    op.create_index(op.f('ix_family_goals_is_archived'), 'family_goals', ['is_archived'], unique=False)
    op.create_table('family_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='invitationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_invitations_deleted_at'), 'family_invitations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_family_invitations_family_id'), 'family_invitations', ['family_id'], unique=False)
    op.create_index('ix_family_invitations_family_status', 'family_invitations', ['family_id', 'status'], unique=False)
    op.create_index(op.f('ix_family_invitations_id'), 'family_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_family_invitations_invite_code'), 'family_invitations', ['invite_code'], unique=True)
    op.create_index(op.f('ix_family_invitations_invited_by'), 'family_invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_family_invitations_status'), 'family_invitations', ['status'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='familyrole', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_member')
    )
    op.create_index(op.f('ix_family_members_deleted_at'), 'family_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_index('ix_family_members_user_active', 'family_members', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('family_reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_reflections_author_id'), 'family_reflections', ['author_id'], unique=False)
    op.create_index(op.f('ix_family_reflections_deleted_at'), 'family_reflections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_family_reflections_family_id'), 'family_reflections', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_reflections_id'), 'family_reflections', ['id'], unique=False)
    op.create_index('ix_family_reflections_list', 'family_reflections', ['family_id', 'created_at'], unique=False)
    op.create_table('family_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_settings_deleted_at'), 'family_settings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_family_settings_family_id'), 'family_settings', ['family_id'], unique=True)
    op.create_index(op.f('ix_family_settings_id'), 'family_settings', ['id'], unique=False)
    op.create_table('prayer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_requests_author_id'), 'prayer_requests', ['author_id'], unique=False)
    op.create_index(op.f('ix_prayer_requests_deleted_at'), 'prayer_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_prayer_requests_family_id'), 'prayer_requests', ['family_id'], unique=False)
    op.create_index(op.f('ix_prayer_requests_id'), 'prayer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_requests_is_answered'), 'prayer_requests', ['is_answered'], unique=False)
    op.create_index('ix_prayer_requests_list', 'prayer_requests', ['family_id', 'is_answered', 'created_at'], unique=False)
    op.create_table('family_goal_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('is_achieved', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['family_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_goal_milestones_deleted_at'), 'family_goal_milestones', ['deleted_at'], unique=False)
    op.create_index('ix_family_goal_milestones_goal', 'family_goal_milestones', ['goal_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_family_goal_milestones_goal_id'), 'family_goal_milestones', ['goal_id'], unique=False)
    op.create_index(op.f('ix_family_goal_milestones_id'), 'family_goal_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_family_goal_milestones_is_achieved'), 'family_goal_milestones', ['is_achieved'], unique=False)
    op.create_table('prayer_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prayer_request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prayer_request_id'], ['prayer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_comments_author_id'), 'prayer_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_prayer_comments_deleted_at'), 'prayer_comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_prayer_comments_id'), 'prayer_comments', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_comments_prayer_request_id'), 'prayer_comments', ['prayer_request_id'], unique=False)
    op.create_table('prayer_request_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prayer_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_type', sa.Enum('AMEEN', 'GRANT_EASE', 'ACCEPT', name='prayerresponsetype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prayer_request_id'], ['prayer_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prayer_request_id', 'user_id', 'response_type', name='uq_prayer_response')
    )
    op.create_index(op.f('ix_prayer_request_responses_id'), 'prayer_request_responses', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_request_responses_prayer_request_id'), 'prayer_request_responses', ['prayer_request_id'], unique=False)
    op.create_index(op.f('ix_prayer_request_responses_user_id'), 'prayer_request_responses', ['user_id'], unique=False)
    op.create_table('reflection_encouragements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reflection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encouragement_type', sa.Enum('MAY_ALLAH_ACCEPT', 'AMEEN', 'BARAKALLAHU_FEEK', 'MAY_ALLAH_INCREASE', name='encouragementtype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reflection_id'], ['family_reflections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reflection_id', 'user_id', 'encouragement_type', name='uq_reflection_encouragement')
    )
    op.create_index(op.f('ix_reflection_encouragements_id'), 'reflection_encouragements', ['id'], unique=False)
    op.create_index(op.f('ix_reflection_encouragements_reflection_id'), 'reflection_encouragements', ['reflection_id'], unique=False)
    op.create_index(op.f('ix_reflection_encouragements_user_id'), 'reflection_encouragements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflection_encouragements_user_id'), table_name='reflection_encouragements')
    op.drop_index(op.f('ix_reflection_encouragements_reflection_id'), table_name='reflection_encouragements')
    op.drop_index(op.f('ix_reflection_encouragements_id'), table_name='reflection_encouragements')
    op.drop_table('reflection_encouragements')
    op.drop_index(op.f('ix_prayer_request_responses_user_id'), table_name='prayer_request_responses')
    op.drop_index(op.f('ix_prayer_request_responses_prayer_request_id'), table_name='prayer_request_responses')
    op.drop_index(op.f('ix_prayer_request_responses_id'), table_name='prayer_request_responses')
    op.drop_table('prayer_request_responses')
    op.drop_index(op.f('ix_prayer_comments_prayer_request_id'), table_name='prayer_comments')
    op.drop_index(op.f('ix_prayer_comments_id'), table_name='prayer_comments')
    op.drop_index(op.f('ix_prayer_comments_deleted_at'), table_name='prayer_comments')
    op.drop_index(op.f('ix_prayer_comments_author_id'), table_name='prayer_comments')
    op.drop_table('prayer_comments')
    op.drop_index(op.f('ix_family_goal_milestones_is_achieved'), table_name='family_goal_milestones')
    op.drop_index(op.f('ix_family_goal_milestones_id'), table_name='family_goal_milestones')
    op.drop_index(op.f('ix_family_goal_milestones_goal_id'), table_name='family_goal_milestones')
    op.drop_index('ix_family_goal_milestones_goal', table_name='family_goal_milestones')
    op.drop_index(op.f('ix_family_goal_milestones_deleted_at'), table_name='family_goal_milestones')
    op.drop_table('family_goal_milestones')
    op.drop_index('ix_prayer_requests_list', table_name='prayer_requests')
    op.drop_index(op.f('ix_prayer_requests_is_answered'), table_name='prayer_requests')
    op.drop_index(op.f('ix_prayer_requests_id'), table_name='prayer_requests')
    op.drop_index(op.f('ix_prayer_requests_family_id'), table_name='prayer_requests')
    op.drop_index(op.f('ix_prayer_requests_deleted_at'), table_name='prayer_requests')
    op.drop_index(op.f('ix_prayer_requests_author_id'), table_name='prayer_requests')
    op.drop_table('prayer_requests')
    op.drop_index(op.f('ix_family_settings_id'), table_name='family_settings')
    op.drop_index(op.f('ix_family_settings_family_id'), table_name='family_settings')
    op.drop_index(op.f('ix_family_settings_deleted_at'), table_name='family_settings')
    op.drop_table('family_settings')
    op.drop_index('ix_family_reflections_list', table_name='family_reflections')
    op.drop_index(op.f('ix_family_reflections_id'), table_name='family_reflections')
    op.drop_index(op.f('ix_family_reflections_family_id'), table_name='family_reflections')
    op.drop_index(op.f('ix_family_reflections_deleted_at'), table_name='family_reflections')
    op.drop_index(op.f('ix_family_reflections_author_id'), table_name='family_reflections')
    op.drop_table('family_reflections')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index('ix_family_members_user_active', table_name='family_members')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_deleted_at'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_family_invitations_status'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_invited_by'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_invite_code'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_id'), table_name='family_invitations')
    op.drop_index('ix_family_invitations_family_status', table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_family_id'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_deleted_at'), table_name='family_invitations')
    op.drop_table('family_invitations')
    op.drop_index(op.f('ix_family_goals_is_archived'), table_name='family_goals')
    op.drop_index(op.f('ix_family_goals_id'), table_name='family_goals')
    op.drop_index(op.f('ix_family_goals_family_id'), table_name='family_goals')
    op.drop_index(op.f('ix_family_goals_deleted_at'), table_name='family_goals')
    op.drop_index(op.f('ix_family_goals_created_by'), table_name='family_goals')
    op.drop_index('ix_family_goals_active', table_name='family_goals')
    op.drop_table('family_goals')
    op.drop_index('ix_family_activities_timeline', table_name='family_activities')
    op.drop_index(op.f('ix_family_activities_id'), table_name='family_activities')
    op.drop_index(op.f('ix_family_activities_family_id'), table_name='family_activities')
    op.drop_index(op.f('ix_family_activities_event_type'), table_name='family_activities')
    op.drop_index(op.f('ix_family_activities_actor_id'), table_name='family_activities')
    op.drop_table('family_activities')
    op.drop_index('ix_activity_sessions_user_started', table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_user_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_started_at'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_family_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_deleted_at'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_created_at'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_context'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_activity_type'), table_name='activity_sessions')
    op.drop_table('activity_sessions')
    op.drop_index('ix_activity_completions_user_type', table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_user_id'), table_name='activity_completions')
    op.drop_index('ix_activity_completions_user_date', table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_id'), table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_family_id'), table_name='activity_completions')
    op.drop_index('ix_activity_completions_family', table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_deleted_at'), table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_created_at'), table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_context'), table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_completed_at'), table_name='activity_completions')
    op.drop_index(op.f('ix_activity_completions_activity_type'), table_name='activity_completions')
    op.drop_table('activity_completions')
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_revoked_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_status'), table_name='user_goals')
    op.drop_index('ix_user_goals_month', table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_deleted_at'), table_name='user_goals')
    op.drop_index('ix_user_goals_active', table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_scheduled_notifications_user_id'), table_name='scheduled_notifications')
    op.drop_index(op.f('ix_scheduled_notifications_scheduled_for'), table_name='scheduled_notifications')
    op.drop_index('ix_scheduled_notifications_due', table_name='scheduled_notifications')
    op.drop_table('scheduled_notifications')
    op.drop_index(op.f('ix_sadaqah_logs_user_id'), table_name='sadaqah_logs')
    op.drop_index(op.f('ix_sadaqah_logs_request_id'), table_name='sadaqah_logs')
    op.drop_index(op.f('ix_sadaqah_logs_id'), table_name='sadaqah_logs')
    op.drop_index(op.f('ix_sadaqah_logs_created_at'), table_name='sadaqah_logs')
    op.drop_index(op.f('ix_sadaqah_logs_act_id'), table_name='sadaqah_logs')
    op.drop_index('idx_user_date', table_name='sadaqah_logs')
    op.drop_index('idx_date', table_name='sadaqah_logs')
    op.drop_table('sadaqah_logs')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_used_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_idempotency_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_monthly_goal_reviews_user_id'), table_name='monthly_goal_reviews')
    op.drop_index(op.f('ix_monthly_goal_reviews_id'), table_name='monthly_goal_reviews')
    op.drop_table('monthly_goal_reviews')
    op.drop_index(op.f('ix_journey_reflections_user_id'), table_name='journey_reflections')
    op.drop_index('ix_journey_reflections_user_date', table_name='journey_reflections')
    op.drop_index(op.f('ix_journey_reflections_id'), table_name='journey_reflections')
    op.drop_index(op.f('ix_journey_reflections_deleted_at'), table_name='journey_reflections')
    op.drop_index(op.f('ix_journey_reflections_date'), table_name='journey_reflections')
    op.drop_index(op.f('ix_journey_reflections_created_at'), table_name='journey_reflections')
    op.drop_table('journey_reflections')
    op.drop_index(op.f('ix_journey_reading_progress_user_id'), table_name='journey_reading_progress')
    op.drop_index(op.f('ix_journey_reading_progress_last_read_at'), table_name='journey_reading_progress')
    op.drop_index(op.f('ix_journey_reading_progress_id'), table_name='journey_reading_progress')
    op.drop_index(op.f('ix_journey_reading_progress_created_at'), table_name='journey_reading_progress')
    op.drop_index(op.f('ix_journey_reading_progress_chapter_number'), table_name='journey_reading_progress')
    op.drop_index(op.f('ix_journey_reading_progress_book_id'), table_name='journey_reading_progress')
    op.drop_table('journey_reading_progress')
    op.drop_index(op.f('ix_journey_adhkar_progress_user_id'), table_name='journey_adhkar_progress')
    op.drop_index(op.f('ix_journey_adhkar_progress_id'), table_name='journey_adhkar_progress')
    op.drop_index(op.f('ix_journey_adhkar_progress_created_at'), table_name='journey_adhkar_progress')
    op.drop_index(op.f('ix_journey_adhkar_progress_adhkar_id'), table_name='journey_adhkar_progress')
    op.drop_table('journey_adhkar_progress')
    op.drop_index(op.f('ix_journey_adhkar_favorites_user_id'), table_name='journey_adhkar_favorites')
    op.drop_index(op.f('ix_journey_adhkar_favorites_id'), table_name='journey_adhkar_favorites')
    op.drop_index(op.f('ix_journey_adhkar_favorites_created_at'), table_name='journey_adhkar_favorites')
    op.drop_index(op.f('ix_journey_adhkar_favorites_adhkar_id'), table_name='journey_adhkar_favorites')
    op.drop_table('journey_adhkar_favorites')
    op.drop_index(op.f('ix_jars_user_id'), table_name='jars')
    op.drop_index(op.f('ix_jars_id'), table_name='jars')
    op.drop_table('jars')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_index(op.f('ix_families_deleted_at'), table_name='families')
    op.drop_index(op.f('ix_families_created_by'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_evidences_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_donation_intents_user_id'), table_name='donation_intents')
    op.drop_index(op.f('ix_donation_intents_charity_id'), table_name='donation_intents')
    op.drop_table('donation_intents')
    op.drop_index(op.f('ix_book_chapters_id'), table_name='book_chapters')
    op.drop_index('ix_book_chapters_book_order', table_name='book_chapters')
    op.drop_index(op.f('ix_book_chapters_book_id'), table_name='book_chapters')
    op.drop_table('book_chapters')
    op.drop_index(op.f('ix_book_bookmarks_user_id'), table_name='book_bookmarks')
    op.drop_index(op.f('ix_book_bookmarks_id'), table_name='book_bookmarks')
    op.drop_index(op.f('ix_book_bookmarks_created_at'), table_name='book_bookmarks')
    op.drop_index(op.f('ix_book_bookmarks_book_id'), table_name='book_bookmarks')
    op.drop_table('book_bookmarks')
    op.drop_index(op.f('ix_activity_streaks_user_id'), table_name='activity_streaks')
    op.drop_index(op.f('ix_activity_streaks_last_completed_at'), table_name='activity_streaks')
    op.drop_index(op.f('ix_activity_streaks_id'), table_name='activity_streaks')
    op.drop_index(op.f('ix_activity_streaks_created_at'), table_name='activity_streaks')
    op.drop_index(op.f('ix_activity_streaks_activity_type'), table_name='activity_streaks')
    op.drop_table('activity_streaks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sadaqah_acts_verified_ramadan', table_name='sadaqah_acts')
    op.drop_index(op.f('ix_sadaqah_acts_id'), table_name='sadaqah_acts')
    op.drop_table('sadaqah_acts')
    op.drop_index(op.f('ix_notification_templates_strategy'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_key'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_enabled'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_category'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_leaderboard_seasons_season_name'), table_name='leaderboard_seasons')
    op.drop_index(op.f('ix_leaderboard_seasons_id'), table_name='leaderboard_seasons')
    op.drop_table('leaderboard_seasons')
    op.drop_index('ix_charities_verified_active_featured', table_name='charities')
    op.drop_index('ix_charities_verified_active_category', table_name='charities')
    op.drop_index(op.f('ix_charities_id'), table_name='charities')
    op.drop_table('charities')
    op.drop_index(op.f('ix_books_published'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_deleted_at'), table_name='books')
    op.drop_index(op.f('ix_books_category'), table_name='books')
    op.drop_table('books')
    op.drop_table('badges')
    op.drop_index(op.f('ix_adhkar_time_of_day'), table_name='adhkar')
    op.drop_table('adhkar')
    # ### end Alembic commands ###
