"""add timezone fields

Revision ID: ef8974187265
Revises: d034c00fc7ca
Create Date: 2026-08-06 13:38:04.736208

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ef8974187265"
down_revision: Union[str, Sequence[str], None] = "d034c00fc7ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
